Repository Shopify/slate, pull requests merged in 2018-02, with the labels that each got.

#392 Remove email link from docs
  docs/_includes/sidebar.html
Labels: documentation

#393 Fix broken email link
  docs/_includes/sidebar.html
Labels: documentation

#400 Add docs on using yarn start with env flag
  README.md
Labels: documentation

#405 Add helpful comments to generated `.env` file
  packages/slate-config/__tests__/index.test.js
  packages/slate-config/index.js
  packages/slate-env/README.md
  packages/slate-env/index.js
  packages/slate-env/slate-env.config.js
Labels: enhancement

#413 Slate tools refactor
  packages/slate-babel/slate-babel.config.js
  packages/slate-common-excludes/slate-common-excludes.config.js
  packages/slate-config/__tests__/fixtures/otherSchema.js
  packages/slate-config/__tests__/fixtures/slate.config.js
  packages/slate-config/__tests__/fixtures/testSchema.js
  packages/slate-config/__tests__/index.test.js
  packages/slate-config/__tests__/validate.test.js
  packages/slate-config/index.js
  packages/slate-cssvar-loader/slate-cssvar-loader.config.js
  packages/slate-env/slate-env.config.js
  packages/slate-rc/slate-rc.config.js
  packages/slate-sync/index.js
  packages/slate-sync/package.json
  packages/slate-sync/prompt-if-published-theme.js
  packages/slate-sync/slate-sync.config.js
  packages/slate-tools/cli/commands/build.js
  packages/slate-tools/cli/commands/deploy.js
  packages/slate-tools/cli/commands/start.js
  packages/slate-tools/cli/commands/zip.js
  packages/slate-tools/cli/index.js
  packages/slate-tools/config/index.js
  packages/slate-tools/config/paths.js
  packages/slate-tools/package.json
  packages/slate-tools/slate-tools.config.js
  packages/slate-tools/tools/webpack/config/core.js
  packages/slate-tools/tools/webpack/config/dev.js
  packages/slate-tools/tools/webpack/config/prod.js
  packages/slate-tools/tools/webpack/get-user-webpack-config.js
  packages/slate-tools/tools/webpack/hmr-alamo-loader.js
  packages/slate-tools/tools/webpack/hot-client.js
  packages/slate-tools/tools/webpack/set-slate-env.js
  packages/slate-tools/tools/webpack/static-files-glob.js
Labels: internal

#417 marks webpack compilation script error with process.exit(1)
  packages/slate-tools/cli/commands/build.js
Labels: internal
