Repository Shopify/slate, pull requests merged in 2018-03, with the labels that each got.

#426 Clearer SCSS Documentation
  README.md
Labels: documentation

#440 Update broken link at theme-scaffold/index.md
  docs/theme-scaffold/index.md
Labels: documentation

#448 Add google_pay as available payment type
  packages/slate-theme/src/sections/footer.liquid
Labels: enhancement, v0.x

#446 Fix Node version check and error
  packages/create-slate-theme/index.js
Labels: bug, v1.x

#445 Default to https when cloning new Slate theme
  packages/create-slate-theme/__mocks__/hosted-git-info.js
  packages/create-slate-theme/__tests__/create-slate-theme.test.js
  packages/create-slate-theme/__tests__/index.test.js
  packages/create-slate-theme/create-slate-theme.config.js
  packages/create-slate-theme/create-slate-theme.js
  packages/create-slate-theme/index.js
Labels: enhancement, v1.x

#439 Prompt user if uploading settings_data.json
  packages/slate-sync/__tests__/prompt-if-settings-data.test.js
  packages/slate-sync/index.js
  packages/slate-sync/package.json
  packages/slate-sync/prompt-skip-settings-data.js
  packages/slate-sync/slate-sync.config.js
  packages/slate-tools/cli/commands/start.js
  yarn.lock
Labels: enhancement

#438 Add lint and format command
  packages/slate-tools/README.md
  packages/slate-tools/cli/commands/format.js
  packages/slate-tools/cli/commands/lint.js
  packages/slate-tools/cli/index.js
  packages/slate-tools/package.json
  packages/slate-tools/slate-tools.config.js
  packages/slate-tools/tools/eslint/__tests__/index.test.js
  packages/slate-tools/tools/eslint/index.js
  packages/slate-tools/tools/prettier/__tests__/index.test.js
  packages/slate-tools/tools/prettier/index.js
  packages/slate-tools/tools/stylelint/__tests__/index.test.js
  packages/slate-tools/tools/stylelint/index.js
  packages/slate-tools/tools/theme-lint/__tests__/index.test.js
  packages/slate-tools/tools/theme-lint/index.js
  yarn.lock
Labels: enhancement

#453 Add --skipPrompts flag
  packages/slate-sync/__tests__/skip-settings-data.test.js
  packages/slate-sync/continue-if-published.js
  packages/slate-sync/index.js
  packages/slate-sync/package.json
  packages/slate-sync/skip-settings-data.js
  packages/slate-tools/cli/commands/start.js
Labels: enhancement, v1.x

#454 Add docs for --skipPrompts flag
  packages/slate-tools/README.md
Labels: documentation, v1.x

#450 Webpack v4. Add template and layout specific JS entrypoints.
  package.json
  packages/create-slate-theme/package.json
  packages/html-webpack-liquid-asset-tags-plugin/index.js
  packages/slate-analytics/package.json
  packages/slate-sync/package.json
  packages/slate-tag-webpack-plugin/index.js
  packages/slate-tools/cli/commands/start.js
  packages/slate-tools/package.json
  packages/slate-tools/slate-tools.config.js
  packages/slate-tools/tools/webpack/config/core.js
  packages/slate-tools/tools/webpack/config/dev.js
  packages/slate-tools/tools/webpack/config/prod.js
  packages/slate-tools/tools/webpack/entrypoints.js
  packages/slate-tools/tools/webpack/get-changed-files.js
  packages/slate-tools/tools/webpack/get-chunk-name.js
  packages/slate-tools/tools/webpack/hot-client.js
  packages/slate-tools/tools/webpack/script-tags.html
  packages/slate-tools/tools/webpack/static-files-glob.js
  packages/slate-tools/tools/webpack/style-tags.html
  yarn.lock
Labels: enhancement, v1.x

#458 Fix fake SSL certificate path in slate-tools start command
  CHANGELOG.md
  lerna.json
  packages/create-slate-theme/package.json
  packages/html-webpack-liquid-asset-tags-plugin/package.json
  packages/slate-analytics/package.json
  packages/slate-babel/package.json
  packages/slate-common-excludes/package.json
  packages/slate-config/package.json
  packages/slate-cssvar-loader/package.json
  packages/slate-env/package.json
  packages/slate-error/package.json
  packages/slate-liquid-asset-loader/package.json
  packages/slate-rc/package.json
  packages/slate-sync/package.json
  packages/slate-tag-webpack-plugin/package.json
  packages/slate-tools/cli/commands/start.js
  packages/slate-tools/package.json
Labels: bug, v1.x
