Repository Shopify/slate, pull requests merged in 2018-10, with the labels that each got.

#812 Fix SLATE_USER_EMAIL env variable not being set for all commands
  packages/slate-env/README.md
  packages/slate-sync/index.js
  packages/slate-tools/cli/commands/deploy.js
  packages/slate-tools/cli/index.js
  packages/slate-tools/tools/asset-server/index.js
  packages/slate-tools/tools/webpack/set-slate-env.js
Labels: bug, v1.x

#815 Remove extra } character in settings-data prompt
  packages/slate-tools/cli/prompts/skip-settings-data.js
Labels: internal, v1.x

#814 Clarify how the the SLATE_IGNORE_FILES env variable works
  packages/slate-env/README.md
Labels: documentation, v1.x

#808 Support customers level template bundles
  packages/slate-tools/tools/webpack/config/utilities/get-template-entrypoints.js
  packages/slate-tools/tools/webpack/script-tags.html
  packages/slate-tools/tools/webpack/style-tags.html
Labels: bug, v1.x

#850 (WIP) Simplify Slate assets
  packages/html-webpack-liquid-asset-tags-plugin/README.md
  packages/html-webpack-liquid-asset-tags-plugin/index.js
  packages/html-webpack-liquid-asset-tags-plugin/package.json
  packages/slate-config/common/paths.schema.js
  packages/slate-liquid-asset-loader/README.md
  packages/slate-liquid-asset-loader/index.js
  packages/slate-liquid-asset-loader/package.json
  packages/slate-tools/slate-tools.schema.js
  packages/slate-tools/tools/asset-server/app.js
  packages/slate-tools/tools/asset-server/client.js
  packages/slate-tools/tools/asset-server/index.js
  packages/slate-tools/tools/utilities/index.js
  packages/slate-tools/tools/webpack/config/dev.js
  packages/slate-tools/tools/webpack/config/parts/core.js
  packages/slate-tools/tools/webpack/config/prod.js
  packages/slate-tools/tools/webpack/config/utilities/get-layout-entrypoints.js
  packages/slate-tools/tools/webpack/static-files-glob.js
  packages/slate-tools/tools/webpack/style-tags.html
  yarn.lock
Labels: breaking, bug, v1.x

#821 Prevent trailing slashes at the end of store URLs
  packages/slate-env/__tests__/index.test.js
  packages/slate-env/index.js
Labels: enhancement, v1.x

#852 Add 'network.externalTesting.address' config
  packages/slate-tools/cli/commands/start.js
  packages/slate-tools/cli/prompts/external-testing.js
  packages/slate-tools/cli/prompts/tests/disable-external-testing.test.js
  packages/slate-tools/cli/prompts/tests/external-testing.test.js
  packages/slate-tools/slate-tools.schema.js
  packages/slate-tools/tools/asset-server/index.js
  packages/slate-tools/tools/dev-server/index.js
Labels: config
