Repository Shopify/slate, pull requests merged in 2018-06, with the labels that each got.

#621 Modified slate-cssvar-loader to allow CSS variables without Liquid variables, V2
  packages/slate-cssvar-loader/__tests__/fixtures/invalid.css
  packages/slate-cssvar-loader/__tests__/index.test.js
  packages/slate-cssvar-loader/index.js
Labels: enhancement, v1.x

#643 Throw an error if we fail to access Theme API
  packages/slate-sync/index.js
  packages/slate-tools/cli/commands/start.js
  packages/slate-tools/cli/prompts/continue-if-published-theme.js
Labels: bug, v1.x

#654 Fix build break when missing fonts directory
  packages/slate-tools/tools/webpack/config/core.js
Labels: bug
