Repository Shopify/slate, pull requests merged in 2018-12, with the labels that each got.

#923 Fix cli:start and start:start analytics events
  packages/slate-tools/cli/commands/start.js
  packages/slate-tools/cli/index.js
Labels: internal

#925 Update analytics to refer to beta instead of alpha
  packages/slate-analytics/prompt.js
Labels: bug, v1.x

#929 Remove unused docs files
  docs/blog/2016/03/11/blog-post.html
  docs/blog/2016/03/11/blog-post/index.html
  docs/blog/2017/04/10/blog-post-two.html
  docs/blog/2017/04/10/blog-post-two/index.html
  docs/blog/2017/09/25/testing-rss.html
  docs/blog/2017/09/25/testing-rss/index.html
  docs/blog/2017/09/26/adding-rss.html
  docs/blog/2017/09/26/adding-rss/index.html
  docs/blog/2017/10/24/new-version-1.0.0.html
  docs/blog/2017/10/24/new-version-1.0.0/index.html
  docs/blog/atom.xml
  docs/blog/feed.xml
  docs/blog/index.html
  docs/sitemap.xml
  docusaurus/v1/blog/2016-03-11-blog-post.md
  docusaurus/v1/blog/2017-04-10-blog-post-two.md
  docusaurus/v1/blog/2017-09-25-testing-rss.md
  docusaurus/v1/blog/2017-09-26-adding-rss.md
  docusaurus/v1/blog/2017-10-24-new-version-1.0.0.md
  docusaurus/v1/build/slate/blog/2016/03/11/blog-post.html
  docusaurus/v1/build/slate/blog/2016/03/11/blog-post/index.html
  docusaurus/v1/build/slate/blog/2017/04/10/blog-post-two.html
  docusaurus/v1/build/slate/blog/2017/04/10/blog-post-two/index.html
  docusaurus/v1/build/slate/blog/2017/09/25/testing-rss.html
  docusaurus/v1/build/slate/blog/2017/09/25/testing-rss/index.html
  docusaurus/v1/build/slate/blog/2017/09/26/adding-rss.html
  docusaurus/v1/build/slate/blog/2017/09/26/adding-rss/index.html
  docusaurus/v1/build/slate/blog/2017/10/24/new-version-1.0.0.html
  docusaurus/v1/build/slate/blog/2017/10/24/new-version-1.0.0/index.html
  docusaurus/v1/build/slate/blog/atom.xml
  docusaurus/v1/build/slate/blog/feed.xml
  docusaurus/v1/build/slate/blog/index.html
  docusaurus/v1/build/slate/sitemap.xml
Labels: documentation
