Repository Shopify/slate, pull requests merged in 2018-04, with the labels that each got.

#474 Add --replace flag to the deploy command
  packages/slate-sync/index.js
  packages/slate-tools/README.md
  packages/slate-tools/cli/commands/deploy.js
Labels: enhancement, v1.x

#478 Fix typo at packages/slate-tools/README.md
  packages/slate-tools/README.md
Labels: documentation, v1.x

#482 Incorrect type checking when building config objects
  packages/slate-config/index.js
Labels: bug, v1.x

#480 Refactor slate-tools start command
  packages/slate-sync/index.js
  packages/slate-sync/slate-sync.config.js
  packages/slate-tools/cli/commands/build.js
  packages/slate-tools/cli/commands/deploy.js
  packages/slate-tools/cli/commands/start.js
  packages/slate-tools/cli/prompts/continue-if-published-theme.js
  packages/slate-tools/cli/prompts/skip-settings-data.js
  packages/slate-tools/cli/prompts/tests/skip-settings-data.test.js
  packages/slate-tools/package.json
  packages/slate-tools/slate-tools.config.js
  packages/slate-tools/tools/dev-server/app.js
  packages/slate-tools/tools/dev-server/client.js
  packages/slate-tools/tools/dev-server/index.js
  packages/slate-tools/tools/dev-server/ssl/index.js
  packages/slate-tools/tools/dev-server/ssl/server.pem
  packages/slate-tools/tools/webpack/get-changed-files.js
  yarn.lock
Labels: internal, v1.x

#488 Add concat-style-loader to handle Liquid Style files
  packages/concat-style-loader/concat.js
  packages/concat-style-loader/index.js
  packages/concat-style-loader/package.json
  packages/concat-style-loader/test/concat.test.js
  packages/concat-style-loader/test/fixtures/another.css
  packages/concat-style-loader/test/fixtures/concatenated.css
  packages/concat-style-loader/test/fixtures/more.css
  packages/concat-style-loader/test/fixtures/other.css
  packages/concat-style-loader/test/fixtures/style.css
  packages/concat-style-loader/test/helpers/app.js
  packages/concat-style-loader/test/helpers/compiler.js
  packages/slate-tools/package.json
  packages/slate-tools/tools/webpack/config/core.js
  packages/slate-tools/tools/webpack/config/dev.js
  packages/slate-tools/tools/webpack/config/prod.js
  packages/slate-tools/tools/webpack/html-webpack-include-chunks.js
  packages/slate-tools/tools/webpack/static-files-glob.js
  packages/slate-tools/tools/webpack/style-tags.html
  yarn.lock
Labels: enhancement, v1.x

#494 Adds concat-style-loader to slate-tools package.json
  packages/slate-tools/package.json
Labels: bug, v1.x

#495 Add path module to dev-server/ssl module
  packages/slate-tools/tools/dev-server/ssl/index.js
Labels: bug, v1.x

#500 Add @import file as dependencies in concat-css-loader
  packages/concat-style-loader/concat.js
  packages/concat-style-loader/index.js
Labels: bug, v1.x

#510 Ignore `@import` statements which are not followed by `url(..)`
  packages/concat-style-loader/concat.js
  packages/concat-style-loader/test/concat.test.js
Labels: enhancement, v1.x

#512 Fix asset url generated in slate-tools start
  packages/slate-liquid-asset-loader/index.js
  packages/slate-tools/cli/commands/start.js
  packages/slate-tools/tools/webpack/config/core.js
  packages/slate-tools/tools/webpack/config/dev.js
  packages/slate-tools/tools/webpack/config/prod.js
Labels: bug, v1.x
